app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

rest : 
  type : rest 
  resource : "@AppBundle/Ressources/config/routing_rest.yml"
  prefix : /api
