<?php

namespace AppBundle\Entity;

/**
 * AdministratorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministratorsRepository extends \Doctrine\ORM\EntityRepository
{
}
