<?php

namespace AppBundle\Entity;

/**
 * BadAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
