<?php

namespace AppBundle\Entity;

/**
 * ClassRoomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassRoomsRepository extends \Doctrine\ORM\EntityRepository
{
}
