<?php

namespace AppBundle\Entity;

/**
 * GoodAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
