<?php

namespace AppBundle\Entity;

/**
 * PersonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonsRepository extends \Doctrine\ORM\EntityRepository
{
}
