<?php

namespace AppBundle\Entity;

/**
 * QCMsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom.
 * repository methods below.
 */
class QCMsRepository extends \Doctrine\ORM\EntityRepository
{
	public function selectName() {
		//SELECT q.nameQcm FROM AppBundle:QCMs q
		$query = $this->createQueryBuilder('q');
		
		return $query->getQuery()->getResult();
	}
}
