<?php

namespace AppBundle\Entity;

/**
 * QCMsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QCMsRepository extends \Doctrine\ORM\EntityRepository
{
}
