<?php

namespace AppBundle\Entity;

/**
 * UsersQcmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersQcmRepository extends \Doctrine\ORM\EntityRepository
{
}
