<?php

namespace AppBundle\Entity;

/**
 * UserAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
